# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_SUPER_ADMIN'
                    user:
                        password: user
                        roles: 'ROLE_USER'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        main:
            pattern:  ^/
            provider: in_memory
            anonymous: ~
            form_login:
                login_path: login
                check_path: /login-check
                use_forward: true
                default_target_path: /
                use_referer: false
                username_parameter: _username
                password_parameter: _password
                post_only: true
                remember_me: true
            logout:
                path: logout
                invalidate_session: false
            remember_me:
                secret: "%secret%"
                lifetime: 3600
                path: /foo
                secure: true
                httponly: true
                always_remember_me: false
                remember_me_parameter: _remember_me

    role_hierarchy:
        ROLE_USER: [ROLE_USER]
        ROLE_ADMIN: [ROLE_USER,ROLE_EVENT_CREATE]
        ROLE_SUPER_ADMIN: [ROLE_USER,ROLE_ADMIN,ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }